version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fichajes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
